import { SEOHead } from '@/components/SEOHead';
import { Breadcrumb } from '@/components/layout/Breadcrumb';

export default function Disclaimer() {
  return (
    <>
      <SEOHead
        title="Disclaimer — OrdStudio"
        description="Review OrdStudio disclaimer. Understand the policies, terms, and guidelines for utilizing our AI design and creation suite."
        canonicalPath="/disclaimer"
      />

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 legal-content">
        <Breadcrumb items={[{ label: 'Disclaimer' }]} />
        <h1 className="text-3xl sm:text-4xl font-bold text-white mt-8 mb-4" style={{ fontFamily: 'Syne, sans-serif' }}>
          Disclaimer
        </h1>
        <p className="text-white/40 text-sm mb-12">Last updated: July 1, 2026</p>
        
        <div className="space-y-8 text-white/60 leading-relaxed">
          
<section>
  <h2>1. General Information Only</h2>
  <p>All information, tools, templates, and content provided on the OrdStudio website and platform are intended for general information and creative design purposes only. We do not provide professional legal, financial, marketing, or medical advice.</p>
  <p>You assume full responsibility for how you utilize the designs, presentations, and texts generated by our Service, and any business decisions made in reliance thereon.</p>
</section>

<section>
  <h2>2. AI-Generated Content Disclaimer</h2>
  <p>OrdStudio utilizes generative artificial intelligence models to create presentation slides, text copywriting, and sticker designs. By using these features, you acknowledge and agree that:</p>
  <ul>
    <li><strong>Inaccuracy:</strong> AI models can occasionally produce inaccurate, misleading, or factually incorrect content (commonly referred to as "hallucinations"). You are solely responsible for fact-checking all text and data before sharing or publishing.</li>
    <li><strong>Bias & Appropriateness:</strong> AI outputs may reflect biases present in their training data. We implement filters, but we do not guarantee that outputs will be free of offensive or biased content.</li>
    <li><strong>Originality & Plagiarism:</strong> AI outputs are constructed probabilistically. While they are usually unique combinations, we do not guarantee that outputs will not resemble copyrighted materials or other AI-generated designs. You should perform independent trademark and copyright checks if using outputs for commercial brands.</li>
  </ul>
</section>

<section>
  <h2>3. No Guarantees on Outcomes</h2>
  <p>We make no representations or warranties that utilizing OrdStudio will result in specific business outcomes, including increased revenue, successful venture funding, higher search engine rankings, or public engagement. Your success depends on factors beyond our control, including your market, product quality, and marketing execution.</p>
</section>

<section>
  <h2>4. Limitation of Liability</h2>
  <p>IN NO EVENT SHALL ORDSTUDIO BE LIABLE FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, OR SPECIAL DAMAGES ARISING OUT OF YOUR USE OF, OR INABILITY TO USE, THE PLATFORM, OR FOR ANY ERRORS OR OMISSIONS IN AI-GENERATED OUTPUTS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
</section>

<section>
  <h2>5. External Links</h2>
  <p>Our website, especially the blog section, may contain links to external, third-party websites that are not operated or controlled by OrdStudio. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites, and we assume no liability for their contents or privacy practices.</p>
</section>

<section>
  <h2>6. Contact Us</h2>
  <p>If you have any questions regarding this Disclaimer, please write to us at ordinance37@gmail.com.</p>
</section>

        </div>
      </div>
    </>
  );
}