import { SEOHead } from '@/components/SEOHead';
import { Breadcrumb } from '@/components/layout/Breadcrumb';
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { Sparkles, ArrowRight, ChevronDown, CheckCircle, Lightbulb } from 'lucide-react';

export default function SVGExport() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const benefits = [
  {
    "title": "Clean XML Output",
    "description": "Our SVG exporter generates well-structured, semantic XML code with organized groups, clear path labels, and readable CSS styles, suitable for developers."
  },
  {
    "title": "Infinite Vector Scalability",
    "description": "Scale your exported graphics from tiny web favicon resolutions up to massive print billboard dimensions without experiencing pixelation or loss of details."
  },
  {
    "title": "Embedded Web Fonts",
    "description": "Typography settings are referenced properly within the SVG attributes, allowing the graphic to load external Google Fonts dynamically when displayed on the web."
  },
  {
    "title": "Full Path Integrity",
    "description": "Bezier curves, custom coordinates, shapes, and strokes are kept as mathematical vector paths, making them fully editable in Adobe Illustrator or Figma."
  }
];
  const useCases = [
  {
    "title": "Logo & Branding Deliverables",
    "description": "Create company logos, brand marks, and signature icons that can be dropped into marketing brochures, websites, and business cards."
  },
  {
    "title": "Developer Assets Hand-off",
    "description": "Design icons, button shapes, and vector decorations on our canvas, export as SVG, and share code directly with web developers for UI integration."
  },
  {
    "title": "Custom SVG Icon Libraries",
    "description": "Create cohesive collections of vector symbols to use across websites, mobile apps, or UI mockups."
  },
  {
    "title": "Physical Laser Cutting & Decals",
    "description": "Export designs with clear vector cut lines for vinyl stickers, laser cutters, merchandise printing, or CNC machines."
  }
];
  const faqs = [
  {
    "question": "What is the advantage of SVG over PNG?",
    "answer": "SVGs are code-based vector files, meaning they are infinitely scalable and have small file sizes. PNGs are raster images that pixelate when enlarged."
  },
  {
    "question": "Can I edit the exported SVG in Adobe Illustrator or Figma?",
    "answer": "Yes. The files follow standard W3C SVG specifications and are fully compatible with vector editing software like Illustrator, Figma, and Inkscape."
  },
  {
    "question": "Are AI-generated stickers exported as vector paths?",
    "answer": "Stickers generated by the AI model are raster PNGs, so they are embedded as raster image nodes within the SVG wrapper. Hand-drawn shapes and vector layers are fully vector."
  },
  {
    "question": "How is text represented in the exported SVG?",
    "answer": "Text is preserved as scalable `<text>` elements. You can select, copy, and edit it. You can also convert text to outlines in your editing software."
  },
  {
    "question": "Is the exported code clean?",
    "answer": "Yes, our exporter purges empty elements, group tags, and redundant styles to ensure the file size is as small and performant as possible."
  }
];
  const stats = [
  {
    "label": "Compliance",
    "value": "W3C SVG 1.1 Standard"
  },
  {
    "label": "File Compression",
    "value": "Minimized XML Output"
  },
  {
    "label": "Compatible Tools",
    "value": "Illustrator, Figma, Sketch"
  },
  {
    "label": "Text Preservation",
    "value": "Standard <text> nodes"
  }
];

  return (
    <div className="bg-[#090909] text-white">
      <SEOHead
        title="SVG Export — Scalable Vector Graphics Export | OrdStudio"
        description="Export your designs as SVG vector files from OrdStudio. Perfect for logos, icons, and illustrations that need to scale to any size without quality loss."
        canonicalPath="/features/svg-export"
      />

      {/* Hero */}
      <section className="relative py-20 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-purple-600/5 to-transparent pointer-events-none" />
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative">
          <Breadcrumb items={[{ label: 'Features', href: '/features' }, { label: 'S V G Export' }]} />
          <div className="mt-8 max-w-3xl">
            <div className="inline-flex items-center gap-2 bg-purple-500/15 border border-purple-500/25 rounded-full px-4 py-1.5 text-xs font-semibold text-purple-300 uppercase tracking-wider mb-6">
              <Sparkles className="w-3.5 h-3.5" />
              ✦ Export
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold text-white mb-6" style={{ fontFamily: 'Syne, sans-serif' }}>
              SVG Export — Scalable Vector Graphics Export
            </h1>
            <p className="text-lg text-white/50 leading-relaxed mb-8 max-w-2xl">
              Export your designs as SVG vector files from OrdStudio. Perfect for logos, icons, and illustrations that need to scale to any size without quality loss.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link
                to="/login"
                className="inline-flex items-center gap-2 bg-gradient-to-r from-purple-600 to-purple-700 text-white font-semibold px-8 py-3.5 rounded-xl hover:shadow-[0_8px_30px_rgba(124,58,237,0.4)] transition-all"
              >
                Try It Free
                <ArrowRight className="w-4 h-4" />
              </Link>
              <Link
                to="/blog"
                className="inline-flex items-center gap-2 border border-white/10 text-white/70 font-semibold px-8 py-3.5 rounded-xl hover:bg-white/5 transition-all"
              >
                Read Guide
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits */}
      <section className="py-16 border-t border-white/[0.05]">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-white mb-4" style={{ fontFamily: 'Syne, sans-serif' }}>
              Core Benefits
            </h2>
            <p className="text-white/50 max-w-2xl mx-auto">
              Discover why creators and businesses prefer OrdStudio's visual creation toolkit.
            </p>
          </div>
          <div className="grid md:grid-cols-2 gap-8">
            {benefits.map((b) => (
              <div key={b.title} className="feature-benefit-card">
                <h3 className="text-lg font-bold text-white mb-2">{b.title}</h3>
                <p className="text-white/55 text-sm leading-relaxed">{b.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Detailed Description & Stats */}
      <section className="py-16 border-t border-white/[0.05]">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-3xl font-bold text-white mb-6" style={{ fontFamily: 'Syne, sans-serif' }}>
                How It Empowers Your Workflow
              </h2>
              <div className="text-white/50 leading-relaxed space-y-4">
                <p>Refining layouts inside vector graphics files is essential. OrdStudio features native SVG exporting that preserves every path coordinate, gradient fill, and typography style created on the design canvas.</p> <p>By outputting clean, clean XML schemas, our exported vectors can be opened in professional design software or embedded directly into HTML files for immediate web usage. This makes the platform a powerful addition to existing creative workflows.</p> <p>Small file sizes, semantic structuring, and CSS styling references mean your vectors will look sharp and load fast on any browser or screen.</p>
              </div>
            </div>
            <div className="bg-[#111111] border border-white/[0.07] rounded-2xl p-8">
              <h3 className="text-lg font-bold text-white mb-6" style={{ fontFamily: 'Syne, sans-serif' }}>Performance Statistics</h3>
              <div className="space-y-6">
                {stats.map((s, i) => (
                  <div key={i} className="flex items-center gap-4">
                    <div className="w-10 h-10 rounded-lg bg-purple-500/10 flex items-center justify-center shrink-0">
                      <CheckCircle className="w-5 h-5 text-purple-400" />
                    </div>
                    <div>
                      <div className="text-sm text-white/40">{s.label}</div>
                      <div className="text-white font-semibold">{s.value}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="py-16 border-t border-white/[0.05]">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-white mb-4" style={{ fontFamily: 'Syne, sans-serif' }}>
              Common Use Cases
            </h2>
            <p className="text-white/50 max-w-2xl mx-auto">
              Explore how different industries use our creative platform.
            </p>
          </div>
          <div className="grid md:grid-cols-2 gap-6">
            {useCases.map((u, i) => (
              <div key={i} className="feature-usecase-card">
                <h3 className="text-lg font-bold text-white mb-2">{u.title}</h3>
                <p className="text-white/50 text-sm leading-relaxed">{u.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQs */}
      <section className="py-16 border-t border-white/[0.05] max-w-3xl mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-white mb-4" style={{ fontFamily: 'Syne, sans-serif' }}>
            Frequently Asked Questions
          </h2>
          <p className="text-white/50 text-sm">
            Everything you need to know about our features.
          </p>
        </div>
        <div className="space-y-3">
          {faqs.map((faq, index) => (
            <div key={index} className="faq-item">
              <button
                onClick={() => setOpenFaq(openFaq === index ? null : index)}
                className="faq-question"
                aria-expanded={openFaq === index}
              >
                <span>{faq.question}</span>
                <ChevronDown className={`w-5 h-5 transition-transform \${openFaq === index ? 'rotate-180' : ''}`} />
              </button>
              {openFaq === index && (
                <div className="faq-answer">
                  {faq.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 border-t border-white/[0.05]">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="bg-gradient-to-br from-purple-600/20 to-purple-800/10 border border-purple-500/20 rounded-3xl p-12 text-center">
            <h2 className="text-2xl sm:text-3xl font-bold text-white mb-4" style={{ fontFamily: 'Syne, sans-serif' }}>
              Start Creating Today
            </h2>
            <p className="text-white/60 mb-8 max-w-xl mx-auto text-sm">
              Save hours of design work. Create presentations, write copywriting, and design vector graphics with OrdStudio.
            </p>
            <Link to="/login" className="inline-flex items-center gap-2 bg-gradient-to-r from-purple-600 to-purple-700 text-white font-semibold px-8 py-3 rounded-xl hover:shadow-[0_8px_30px_rgba(124,58,237,0.4)] transition-all">
              Get Started Now
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}