import { useState } from 'react';
import { FileText, Download, Copy, Sparkles } from 'lucide-react';

const contentTypes = [
  { id: 'essay', name: 'Essay', icon: '📝', desc: 'Academic essays and papers' },
  { id: 'article', name: 'Article', icon: '📰', desc: 'Blog posts and articles' },
  { id: 'assignment', name: 'Assignment', icon: '📚', desc: 'School assignments' },
  { id: 'lyrics', name: 'Lyrics', icon: '🎵', desc: 'Song lyrics and poetry' },
];

const tones = ['Professional', 'Creative', 'Academic', 'Casual', 'Formal'];

export function ContentGenerator() {
  const [selectedType, setSelectedType] = useState('essay');
  const [topic, setTopic] = useState('');
  const [tone, setTone] = useState('Professional');
  const [wordCount, setWordCount] = useState('500');
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setGeneratedContent(
        `# ${topic || 'Sample Content'}\n\nThis is a sample generated content in ${tone.toLowerCase()} tone. In a real implementation, this would be generated by an AI model based on your requirements.\n\nThe content would be approximately ${wordCount} words long and would match the ${contentTypes.find(t => t.id === selectedType)?.name.toLowerCase()} format you selected.\n\n## Key Points\n\n- Professional AI-generated content\n- Customizable tone and style\n- Ready to use and edit\n- Download in multiple formats\n\n## Conclusion\n\nThis demonstrates the content generation capability of Ord-SevenEight platform.`
      );
      setIsGenerating(false);
    }, 2000);
  };

  return (
    <div className="flex-1 overflow-auto relative z-10">
      <div className="max-w-7xl mx-auto p-8">
        <div className="mb-8">
          <h2 className="text-3xl font-bold text-gray-900">AI Content Generator</h2>
          <p className="text-gray-600 mt-2">Generate high-quality content in seconds</p>
        </div>

        <div className="grid grid-cols-3 gap-6">
          <div className="col-span-1 space-y-6">
            <div className="backdrop-blur-xl bg-white/70 rounded-2xl p-6 border border-gray-200/50 shadow-xl">
              <h3 className="font-bold text-gray-900 mb-4">Content Type</h3>
              <div className="grid grid-cols-2 gap-3">
                {contentTypes.map((type) => (
                  <button
                    key={type.id}
                    onClick={() => setSelectedType(type.id)}
                    className={`p-4 rounded-xl border-2 transition-all text-left ${
                      selectedType === type.id
                        ? 'border-purple-600 bg-purple-50 shadow-lg'
                        : 'border-gray-200 hover:border-gray-300 hover:bg-white/90'
                    }`}
                  >
                    <div className="text-2xl mb-2">{type.icon}</div>
                    <div className="font-medium text-gray-900 text-sm">{type.name}</div>
                  </button>
                ))}
              </div>
            </div>

            <div className="backdrop-blur-xl bg-white/70 rounded-2xl p-6 border border-gray-200/50 shadow-xl">
              <h3 className="font-bold text-gray-900 mb-4">Settings</h3>
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Topic</label>
                  <input
                    type="text"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="Enter your topic..."
                    className="w-full px-3 py-2 border border-gray-300 backdrop-blur-lg bg-white/70 text-gray-900 placeholder-gray-500 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-600"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Tone</label>
                  <select
                    value={tone}
                    onChange={(e) => setTone(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 backdrop-blur-lg bg-white/70 text-gray-900 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-600"
                  >
                    {tones.map((t) => (
                      <option key={t} value={t}>{t}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Word Count</label>
                  <input
                    type="number"
                    value={wordCount}
                    onChange={(e) => setWordCount(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 backdrop-blur-lg bg-white/70 text-gray-900 placeholder-gray-500 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-600"
                  />
                </div>
              </div>
              <button
                onClick={handleGenerate}
                disabled={isGenerating}
                className="w-full mt-6 px-4 py-3 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-xl font-medium hover:shadow-xl hover:scale-105 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
              >
                {isGenerating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles size={18} />
                    Generate Content
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="col-span-2">
            <div className="backdrop-blur-xl bg-white/70 rounded-2xl p-6 border border-gray-200/50 shadow-xl min-h-[600px] flex flex-col">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-bold text-gray-900">Generated Content</h3>
                {generatedContent && (
                  <div className="flex gap-2">
                    <button className="p-2 hover:bg-white/50 backdrop-blur-lg rounded-xl transition-colors text-gray-700 border border-gray-200/50" title="Copy">
                      <Copy size={18} />
                    </button>
                    <button className="px-4 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-xl hover:shadow-xl hover:scale-105 transition-all flex items-center gap-2">
                      <Download size={18} />
                      Download
                    </button>
                  </div>
                )}
              </div>
              {generatedContent ? (
                <div className="flex-1 overflow-auto">
                  <div className="prose max-w-none">
                    {generatedContent.split('\n').map((line, i) => (
                      <p key={i} className="mb-3 text-gray-700">{line}</p>
                    ))}
                  </div>
                </div>
              ) : (
                <div className="flex-1 flex items-center justify-center text-gray-400">
                  <div className="text-center">
                    <FileText size={64} className="mx-auto mb-4 opacity-50" />
                    <p>Your generated content will appear here</p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
