// Master Assembler, Auditor & Exporter for 300 Bespoke Templates
import fs from "fs";
import path from "path";
import { generatePresentations50 } from "./make_presentations_diverse.mjs";
import { generateResumes40 } from "./make_resumes_diverse.mjs";
import { generatePosters50 } from "./make_posters_diverse.mjs";
import { generateFlyers40 } from "./make_flyers_diverse.mjs";
import { generateInvitations35 } from "./make_all_300_master_diverse.mjs";
import { generateBusiness40 } from "./make_business_diverse.mjs";
import { generateReports45 } from "./make_reports_diverse.mjs";
import { auditTemplateLibraryDiversity } from "./designFingerprint.mjs";

console.log("=================================================================");
console.log("ORD STUDIO: ASSEMBLING & AUDITING 300 BESPOKE TEMPLATES");
console.log("=================================================================");

const presentations = generatePresentations50();
const resumes = generateResumes40();
const posters = generatePosters50();
const flyers = generateFlyers40();
const invitations = generateInvitations35();
const business = generateBusiness40();
const reports = generateReports45();

console.log(`- Presentations: ${presentations.length}`);
console.log(`- Resumes:       ${resumes.length}`);
console.log(`- Posters:       ${posters.length}`);
console.log(`- Flyers:        ${flyers.length}`);
console.log(`- Invitations:   ${invitations.length}`);
console.log(`- Business:      ${business.length}`);
console.log(`- Reports:       ${reports.length}`);

const all300 = [
  ...presentations,
  ...resumes,
  ...posters,
  ...flyers,
  ...invitations,
  ...business,
  ...reports
];

console.log(`Total Templates Assembled: ${all300.length}`);

// Perform Global Quality Audit
console.log("\nExecuting Comprehensive Design DNA & Uniqueness Audit across 300 Templates...");
const auditResult = auditTemplateLibraryDiversity(all300, 0.78);

console.log(`\nAudit Results:`);
console.log(`- Total Templates:     ${auditResult.totalTemplates}`);
console.log(`- Duplicate Pairs:     ${auditResult.duplicateCount}`);
console.log(`- Duplicate Images:    ${auditResult.duplicateImages.length}`);
console.log(`- Diversity Pass:      ${auditResult.diversityPass ? "PASSED (100% Unique Design DNA)" : "FAILED"}`);
console.log(`- Image Health Pass:   ${auditResult.imageHealthPass ? "PASSED (100% Unique Assets)" : "FAILED"}`);

if (!auditResult.diversityPass || !auditResult.imageHealthPass) {
  console.error("\n[ERROR] Audit failed! Duplicates detected:");
  console.error(JSON.stringify(auditResult.duplicatePairs.slice(0, 10), null, 2));
  if (auditResult.duplicateImages.length > 0) {
    console.error("Duplicate Images:", JSON.stringify(auditResult.duplicateImages, null, 2));
  }
  process.exit(1);
}

console.log("\n>>> ALL QUALITY GATES PASSED PERFECTLY! EXPORTING CANONICAL TEMPLATES <<<");

// 1. Export to Frontend: artifacts/creative-studio/src/app/lib/canonicalTemplates.ts
const frontendTarget = path.resolve("artifacts/creative-studio/src/app/lib/canonicalTemplates.ts");
const canonicalContent = `// CANONICAL TEMPLATES (300 100% UNIQUE BESPOKE TEMPLATES - ZERO REPETITION)
// Generated by ORD Studio Design DNA Engine

export interface TemplateElement {
  id: string;
  type: string;
  x: number;
  y: number;
  width: number;
  height: number;
  text?: string;
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: string;
  fill?: string;
  stroke?: string;
  strokeWidth?: number;
  borderRadius?: number;
  textAlign?: "left" | "center" | "right" | "justify";
  src?: string;
  locked?: boolean;
  opacity?: number;
  lineHeight?: number;
  letterSpacing?: number;
}

export interface CanonicalTemplate {
  id: number;
  name: string;
  title: string;
  category: string;
  canvasWidth: number;
  canvasHeight: number;
  elements?: TemplateElement[];
  slides?: TemplateElement[][];
  tags: string[];
}

export const CANONICAL_TEMPLATES: CanonicalTemplate[] = ${JSON.stringify(all300, null, 2)};

export const CANONICAL_FALLBACK_TEMPLATES = CANONICAL_TEMPLATES;
export const canonicalTemplates = CANONICAL_TEMPLATES;
export default CANONICAL_TEMPLATES;
`;

fs.writeFileSync(frontendTarget, canonicalContent, "utf-8");
console.log(`Exported ${all300.length} templates to: ${frontendTarget}`);

// 2. Export to Backend Seed Data: artifacts/api-server/src/lib/templateSeedData.ts
const backendTarget = path.resolve("artifacts/api-server/src/lib/templateSeedData.ts");
const backendContent = `// Master Seed Data for API Server (300 100% Unique Bespoke Templates)
export const templateSeedData = ${JSON.stringify(all300, null, 2)};
`;

fs.writeFileSync(backendTarget, backendContent, "utf-8");
console.log(`Exported seed data to: ${backendTarget}`);

// // 3. Export to Backend dbFallback.ts
const fallbackTarget = path.resolve("artifacts/api-server/src/lib/dbFallback.ts");
const dbFallbackSource = 'import { templateSeedData as seededTemplates } from "./templateSeedData";\n\n' +
'export const fallbackTemplates = [...seededTemplates];\n\n' +
'let inMemoryTemplates = [...seededTemplates];\n\n' +
'let inMemoryProjects: any[] = [\n' +
'  {\n' +
'    id: "proj-demo-1",\n' +
'    name: "Brand Pitch Deck",\n' +
'    type: "Presentation",\n' +
'    gradient: "from-blue-600 to-indigo-700",\n' +
'    progress: 85,\n' +
'    updatedAt: new Date().toISOString(),\n' +
'    canvasWidth: 1920,\n' +
'    canvasHeight: 1080,\n' +
'    slides: inMemoryTemplates.find(t => t.id === 101)?.slides || []\n' +
'  }\n' +
'];\n\n' +
'let inMemoryStickers: any[] = [\n' +
'  { id: "stk-1", name: "Star Sparkle", url: "https://api.iconify.design/lucide:sparkles.svg?color=%236366f1", category: "Decor" },\n' +
'  { id: "stk-2", name: "Flame", url: "https://api.iconify.design/lucide:flame.svg?color=%23ef4444", category: "Shapes" },\n' +
'  { id: "stk-3", name: "Heart", url: "https://api.iconify.design/lucide:heart.svg?color=%23ec4899", category: "Icons" }\n' +
'];\n\n' +
'let inMemoryBlogPosts: any[] = [\n' +
'  {\n' +
'    id: "blog-1",\n' +
'    title: "10 Design Principles for High-Converting Presentations",\n' +
'    slug: "10-design-principles-high-converting-presentations",\n' +
'    excerpt: "Master the subtle art of visual hierarchy, negative space, and storytelling in business decks.",\n' +
'    content: "When presenting high-stakes ideas, clarity and structure always outperform visual noise...",\n' +
'    author: "Alex Rivers",\n' +
'    tagsText: "Design,Presentations,Storytelling",\n' +
'    likes: 42,\n' +
'    createdAt: new Date().toISOString()\n' +
'  },\n' +
'  {\n' +
'    id: "blog-2",\n' +
'    title: "The Future of Vector Canvas & Generative Graphics",\n' +
'    slug: "future-of-vector-canvas-generative-graphics",\n' +
'    excerpt: "How real-time canvas architectures are transforming professional design workflows.",\n' +
'    content: "Vector-first workflows provide infinite scalability without degrading fidelity...",\n' +
'    author: "Jordan Lee",\n' +
'    tagsText: "Technology,Vectors,Creative",\n' +
'    likes: 89,\n' +
'    createdAt: new Date().toISOString()\n' +
'  }\n' +
'];\n\n' +
'let inMemoryBlogComments: any[] = [\n' +
'  {\n' +
'    id: "c-1",\n' +
'    slug: "10-design-principles-high-converting-presentations",\n' +
'    author: "Elena Rostova",\n' +
'    content: "The tip on high-contrast focal points immediately improved our seed round pitch deck!",\n' +
'    createdAt: new Date().toISOString()\n' +
'  }\n' +
'];\n\n' +
'let inMemoryContactSubmissions: any[] = [];\n\n' +
'export const dataStore = {\n' +
'  async getTemplates() { return [...inMemoryTemplates]; },\n' +
'  async getTemplateById(id: string | number) {\n' +
'    const numId = Number(id);\n' +
'    return inMemoryTemplates.find(t => t.id === numId || String(t.id) === String(id)) || null;\n' +
'  },\n' +
'  async addTemplate(tpl: any) {\n' +
'    const newTpl = { ...tpl, id: tpl.id || (Date.now()) };\n' +
'    inMemoryTemplates.unshift(newTpl);\n' +
'    return newTpl;\n' +
'  },\n' +
'  async updateTemplate(id: string | number, data: any) {\n' +
'    const idx = inMemoryTemplates.findIndex(t => String(t.id) === String(id));\n' +
'    if (idx !== -1) {\n' +
'      inMemoryTemplates[idx] = { ...inMemoryTemplates[idx], ...data };\n' +
'      return inMemoryTemplates[idx];\n' +
'    }\n' +
'    return null;\n' +
'  },\n' +
'  async deleteTemplate(id: string | number) {\n' +
'    const idx = inMemoryTemplates.findIndex(t => String(t.id) === String(id));\n' +
'    if (idx !== -1) {\n' +
'      const removed = inMemoryTemplates.splice(idx, 1);\n' +
'      return removed[0];\n' +
'    }\n' +
'    return null;\n' +
'  },\n' +
'  async seedTemplates() {\n' +
'    inMemoryTemplates = [...seededTemplates];\n' +
'    return inMemoryTemplates.length;\n' +
'  },\n' +
'  async getProjects() { return [...inMemoryProjects]; },\n' +
'  async saveProject(data: any) {\n' +
'    const id = data.id || "proj-" + Date.now();\n' +
'    const idx = inMemoryProjects.findIndex(p => p.id === id);\n' +
'    const proj = { ...data, id, updatedAt: new Date().toISOString() };\n' +
'    if (idx !== -1) {\n' +
'      inMemoryProjects[idx] = { ...inMemoryProjects[idx], ...proj };\n' +
'    } else {\n' +
'      inMemoryProjects.unshift(proj);\n' +
'    }\n' +
'    return proj;\n' +
'  },\n' +
'  async getStickers() { return [...inMemoryStickers]; },\n' +
'  async addSticker(stk: any) {\n' +
'    const created = { ...stk, id: stk.id || "stk-" + Date.now() };\n' +
'    inMemoryStickers.unshift(created);\n' +
'    return created;\n' +
'  },\n' +
'  async getBlogPosts() { return [...inMemoryBlogPosts]; },\n' +
'  async getBlogPostBySlug(slug: string) {\n' +
'    return inMemoryBlogPosts.find(b => b.slug === slug) || null;\n' +
'  },\n' +
'  async getBlogComments(slug: string) {\n' +
'    return inMemoryBlogComments.filter(c => c.slug === slug);\n' +
'  },\n' +
'  async likeBlogPost(slug: string) {\n' +
'    const post = inMemoryBlogPosts.find(b => b.slug === slug);\n' +
'    if (post) {\n' +
'      post.likes = (post.likes || 0) + 1;\n' +
'      return post;\n' +
'    }\n' +
'    return null;\n' +
'  },\n' +
'  async addBlogComment(slug: string, author: string, content: string) {\n' +
'    const comment = {\n' +
'      id: "c-" + Date.now(),\n' +
'      slug,\n' +
'      author,\n' +
'      content,\n' +
'      createdAt: new Date().toISOString()\n' +
'    };\n' +
'    inMemoryBlogComments.push(comment);\n' +
'    return comment;\n' +
'  },\n' +
'  async saveContactSubmission(data: any) {\n' +
'    const sub = { ...data, id: "sub-" + Date.now(), createdAt: new Date().toISOString() };\n' +
'    inMemoryContactSubmissions.push(sub);\n' +
'    return sub;\n' +
'  }\n' +
'};\n';
fs.writeFileSync(fallbackTarget, dbFallbackSource, "utf-8");
console.log(`Exported dbFallback to: ${fallbackTarget}`);



// 4. Generate Visual Contact Sheet HTML for Verification
const contactSheetTarget = path.resolve("artifacts/creative-studio/public/contact_sheet.html");
const contactSheetHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>ORD Studio — 300 Templates Diversity Audit Contact Sheet</title>
  <style>
    body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #09090b; color: #f4f4f5; padding: 32px; }
    h1 { font-size: 28px; margin-bottom: 8px; color: #ffffff; }
    .stats { display: flex; gap: 24px; margin-bottom: 32px; background: #18181b; padding: 16px 24px; border-radius: 12px; border: 1px solid #27272a; }
    .stat-box { font-size: 14px; color: #a1a1aa; }
    .stat-val { font-size: 24px; font-weight: 800; color: #10b981; margin-top: 4px; }
    .categories { margin-bottom: 24px; display: flex; gap: 12px; flex-wrap: wrap; }
    .cat-btn { background: #27272a; color: #e4e4e7; border: none; padding: 8px 16px; border-radius: 8px; cursor: pointer; font-weight: 600; }
    .cat-btn.active { background: #3b82f6; color: #ffffff; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 20px; }
    .card { background: #18181b; border-radius: 12px; border: 1px solid #27272a; padding: 12px; display: flex; flex-direction: column; }
    .preview-box { width: 100%; aspect-ratio: 1200 / 1697; background: #000; border-radius: 8px; overflow: hidden; position: relative; }
    .preview-box.pres { aspect-ratio: 1920 / 1080; }
    .info { margin-top: 12px; font-size: 13px; }
    .info .name { font-weight: 700; color: #ffffff; }
    .info .meta { color: #71717a; font-size: 11px; margin-top: 4px; }
  </style>
</head>
<body>
  <h1>ORD Studio — 300 Unique Templates Contact Sheet</h1>
  <div class="stats">
    <div class="stat-box">Total Templates<div class="stat-val">300</div></div>
    <div class="stat-box">Duplicate Pairs<div class="stat-val">0</div></div>
    <div class="stat-box">Duplicate Photos<div class="stat-val">0</div></div>
    <div class="stat-box">Diversity Quality Gate<div class="stat-val">100% PASSED</div></div>
  </div>
  <div class="grid" id="grid"></div>
  <script>
    const templates = ${JSON.stringify(all300.map(t => ({ id: t.id, name: t.name, title: t.title, category: t.category, canvasWidth: t.canvasWidth, canvasHeight: t.canvasHeight, elementCount: t.elements?.length || t.slides?.[0]?.length || 0, tags: t.tags })), null, 2)};
    const grid = document.getElementById('grid');
    templates.forEach(t => {
      const card = document.createElement('div');
      card.className = 'card';
      const isPres = t.category === 'Presentation';
      card.innerHTML = \`
        <div class="preview-box \${isPres ? 'pres' : ''}" id="p-\${t.id}">
          <div style="padding: 16px; font-size: 12px; color: #a1a1aa; text-align: center;">\${t.category} #\${t.id}</div>
        </div>
        <div class="info">
          <div class="name">\${t.title}</div>
          <div class="meta">\${t.category} • \${t.elementCount} elements • \${t.canvasWidth}x\${t.canvasHeight}</div>
        </div>
      \`;
      grid.appendChild(card);
    });
  </script>
</body>
</html>`;

fs.writeFileSync(contactSheetTarget, contactSheetHtml, "utf-8");
console.log(`Exported contact sheet to: ${contactSheetTarget}`);

console.log("\n=================================================================");
console.log("300 TEMPLATES DIVERSITY SYSTEM COMPLETELY EXECUTED & VERIFIED!");
console.log("=================================================================");
