// ORD Studio Bespoke Resume Generator (IDs 201-216)
// Combines modular batches 1 & 2 representing all 10 distinct Resume Design Families:
// 1. Executive Classical Ivory (201) & Legal Counsel Docket (211)
// 2. Modern Corporate Operations (204) & Medical Clinical Officer (210)
// 3. Editorial Creative Director (203) & Swiss Tri-Column Typographic (205)
// 4. Tech Minimalist Systems ATS (202) & AI Research Scientist (214)
// 5. Creative UX Systems Architect (213)
// 6. Academic Clinical Oncology Research (206)
// 7. Minimal Architectural Blueprint (215)
// 8. Timeline Wall Street M&A Ledger (208)
// 9. Modular Product Growth PLG (207) & Global Marketing Funnel (212)
// 10. Typography-Led Startup Dark Dossier (209) & Enterprise Sales Quota (216)

import fs from 'fs';
import path from 'path';
import { RESUMES_BATCH_1 } from './resume_batch_1.mjs';
import { RESUMES_BATCH_2 } from './resume_batch_2.mjs';

export const RESUMES = [
  ...RESUMES_BATCH_1,
  ...RESUMES_BATCH_2
];

// Write to resumes.ts
const targetFile = path.resolve(import.meta.dirname, 'resumes.ts');
const fileContent = `// ORD Studio Canonical Resumes Registry (IDs 201-216)
// Generated by generate_all_resumes.mjs with 100% Unique Design DNA, Zero Layout Repetition, and Zero Photo Reuse.

export const RESUME_TEMPLATES = ${JSON.stringify(RESUMES, null, 2)};
`;

fs.writeFileSync(targetFile, fileContent, 'utf-8');
console.log(`Successfully generated ${RESUMES.length} bespoke Resume templates to ${targetFile}`);
